INSERT INTO paises (nombre) VALUES ('Colombia');
INSERT INTO regiones (pais_id,nombre) VALUES (1,'Santander');
INSERT INTO ciudades (region_id,nombre) VALUES (1,'Bucaramanga');
INSERT INTO categorias_antiguedades (nombre) VALUES ('Esferica');
INSERT INTO galerias (url) VALUES ('imagen.png');
INSERT INTO ranking (votos) VALUES (10);
INSERT INTO epoca_antiguedades (nombre) VALUES ('Colonias');
INSERT INTO antiguedades(categoria_id,ciudad_id,epoca_antiguedad_id,galeria_id,ranking_antiguedad_id,nombre) VALUES (1,1,1,1,1,'Espada de Simon Bolivar');
INSERT INTO detalle_transacciones (antiguedad_id,fecha_transaccion) VALUES (1,'01/08/2023');
INSERT INTO tipo_transaccion (nombre) VALUES ('Bancaria');
INSERT INTO despachos (nombre_despacho) VALUES ('Con cariño');
INSERT INTO medio_pagos (nombre) VALUES ('Banco Aval');
INSERT INTO tipo_mov_caja (nombre) VALUES ('Horario de Mañana');
INSERT INTO estacion_pagos (nombre) VALUES ('caja 1');
INSERT INTO mov_cajas (estacion_pago_id,tip_mov_caja_id) VALUES (1,1);
INSERT INTO tipo_persona (nombre) VALUES ('Natural');
INSERT INTO clase_contacto (nombre) VALUES ('Personal');
INSERT INTO clase_contacto (nombre) VALUES ('Casa');
INSERT INTO contacto_persona (numero,clase_contacto_id) VALUES (3542,1);
INSERT INTO contacto_persona (numero,clase_contacto_id) VALUES (6224,2);
INSERT INTO tipo_direccion (nombre) VALUES ('Residencia Secundaria');
INSERT INTO tipo_direccion (nombre) VALUES ('Residencia Oficial');
INSERT INTO direccion_persona (tipodireccion_id,direccion) VALUES (1,'Cll 85 - 90 - 16');
INSERT INTO direccion_persona (tipodireccion_id,direccion) VALUES (2,'Cll 25 - 47 - 63');
INSERT INTO estado_persona (nombre) VALUES ('Activo');
INSERT INTO estado_persona (nombre) VALUES ('Inactivo');
INSERT INTO generos (nombre) VALUES ('Femenino');
INSERT INTO generos (nombre) VALUES ('Masculino');
INSERT INTO persona_tipo_persona (tipo_persona_id) VALUES (1);
INSERT INTO personas (contacto_persona_id,d_ireccion_persona_id,estado_persona_id,genero_id,persona_tipo_persona_id,edad,nombre) VALUES (1,1,1,1,1,25,'Mario Ruiz');
INSERT INTO personas (contacto_persona_id,d_ireccion_persona_id,estado_persona_id,genero_id,persona_tipo_persona_id,edad,nombre) VALUES (2,2,2,2,1,22,'Celia Cruz');
INSERT INTO coleccionistas (numero_colecciones,persona_id) VALUES (12,1);
INSERT INTO empleados (persona_id,cargo) VALUES (2,'Vendedora');
INSERT INTO transaccion_medio_pago (medio_pago_id) VALUES (1);
INSERT INTO transacciones (despacho_id,detalle_transaccion_id,estacion_pago_id,persona_id,tipo_transaccion_id,transaccion_medio_pago_id) VALUES (1,1,1,1,1,1);
INSERT INTO sucursales (antiguedad_id,ciudad_id,persona_id,nombre) VALUES (1,1,1,'Sucursal Central');
INSERT INTO empresas (sucursal_id,fecha_fundacion,nombre) VALUES (1,'15/02/1900','Antiguedades Selling');
INSERT INTO historial (antiguedad_id,persona_id) VALUES (1,1);
